# Updated : 2026.02.01
# Version : 1.0.0
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

substitutions:
  # --- CATEGORY DICTIONARY ---
  # Use these human-readable names in component yaml substitutions, up to 16 categories
  CAT_SYSTEM:      "0"
  CAT_BMS:         "1"
  CAT_INV_CAN_BUS: "2"
  CAT_INV_RS485:   "3"
  CAT_SHUNT:       "4"
  CAT_BALANCER:    "5"
  CAT_NETWORK:     "6"
  CAT_AUX_1:       "7"

globals:

  # Tracks True/False fault status for every component instance
  # Structure: [Component Category (0-15)] -> [Specific Instance ID (0-N)]
  - id: global_instance_faults
    type: std::vector<std::vector<bool>>
    initial_value: std::vector<std::vector<bool>>(16) 
    restore_value: false

  # Component Fault Bitmask: A 16-bit summary of the component instance health.
  # If Bit 4 is "1", it means "At least one instance in Category 4 is failing."
  - id: global_system_fault_mask
    type: uint16_t
    initial_value: '0'
    restore_value: false

  # ---------------------------------------------------------
  # Global Function: Update Fault Status
  # ---------------------------------------------------------
  - id: global_update_fault
    type: std::function<void(int, int, bool)>
    # Function to update fault status
    initial_value: |-
      [](int category, int instance, bool is_failing) {
        // Convert to zero-based index
        int computer_instance = instance - 1;

        // Validate inputs
        if (category < 0 || category >= 16 || computer_instance < 0) return;

        // Update the fault status
        // Use 'id' to access the other global variable safely
        auto &faults = id(global_instance_faults)[category];
        
        // Resize if this is a higher instance ID
        if (computer_instance >= faults.size()) {
           faults.resize(computer_instance + 1, false);
        }

        faults[computer_instance] = is_failing;
      }


interval:
  # Summarize faults (Every 250ms)
  # Scans the detailed global_instance_faults data to build the global_system_fault_mask
  - interval: 250ms
    then:
      - lambda: |-
          uint16_t summary_mask = 0;
          for (int category = 0; category < 16; category++) {
            for (bool faulted : id(global_instance_faults)[category]) {
              if (faulted) {
                summary_mask |= (1 << category);
                break; // One fault in a category is enough to trigger the bit
              }
            }
          }
          id(global_system_fault_mask) = summary_mask;