# Updated : 2026.02.01
# Version : 1.0.0
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

globals:

  # Tracks True/False fault status for every component instance
  # Structure: [Component Category (0-15)] -> [Specific Instance ID (0-N)]
  - id: global_instance_faults
    type: std::vector<std::vector<bool>>
    initial_value: 'std::vector<std::vector<bool>>(16)'

  # Component Fault Bitmask: A 16-bit summary of the component instance health.
  # If Bit 4 is "1", it means "At least one instance in Category 4 is failing."
  - id: global_system_fault_mask
    type: uint16_t
    initial_value: '0'

esphome:
  includes:
    - source: |
        // --- CATEGORY DICTIONARY ---
        // Use these human-readable names in component yaml substitutions, up to 16 categories
        // #undef commands ensure that even if an add-on package tries to overwite the definition,
        // the main registry overrides them
        #undef CAT_SYSTEM
        #define CAT_SYSTEM        0

        #undef CAT_BMS
        #define CAT_BMS           1

        #undef CAT_INV_CAN_BUS
        #define CAT_INV_CAN_BUS   2

        #undef CAT_INV_RS485
        #define CAT_INV_RS485     3

        #undef CAT_SHUNT
        #define CAT_SHUNT         4

        #undef CAT_BALANCER
        #define CAT_BALANCER      5

        #undef CAT_NETWORK
        #define CAT_NETWORK       6

        #undef CAT_AUX_1
        #define CAT_AUX_1         7

        using namespace esphome;

        /** * API FUNCTION: Updates the fault status of a component.
        * @param category: The Category ID.
        * @param instance: The instance ID of the hardware unit.
        * @param is_failing: True = Fault Active, False = Healthy.
        */
        void update_fault_status(int category, int instance, bool is_failing) {
          int indexed_instance = instance - 1; // Convert to zero-based index
          if (category < 0 || category >= 16 || indexed_instance < 0) return;
          
          // Only update if the instance has been registered/sized correctly
          if (indexed_instance < id(global_instance_faults)[category].size()) {
            id(global_instance_faults)[category][indexed_instance] = is_failing;
          }
        }

interval:
  # Summarize faults (Every 250ms)
  # Scans the detailed global_instance_faults data to build the global_system_fault_mask
  - interval: 250ms
    then:
      - lambda: |-
          uint16_t summary_mask = 0;
          for (int category = 0; category < 16; category++) {
            for (bool faulted : id(global_instance_faults)[category]) {
              if (faulted) {
                summary_mask |= (1 << category);
                break; // One fault in a category is enough to trigger the bit
              }
            }
          }
          id(global_system_fault_mask) = summary_mask;