# Updated : 2026.01.31
# Version : 1.1.2
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.


substitutions:
  global_status_led: "esp_light"


globals:
  # 2D grid of physical LED pointers
  # Structure: [Component Category (0-15)] -> [Specific Instance ID (0-N)]
  - id: global_led_registry
    type: std::vector<std::vector<esphome::light::LightState*>>
    initial_value: 'std::vector<std::vector<esphome::light::LightState*>>(16)'

  # ---------------------------------------------------------
  # Global Function: Update LED assignment
  # ---------------------------------------------------------
  - id: global_register_led
    type: std::function<void(int, int, light::LightState*)>
    initial_value: |-
      [](int category, int instance, light::LightState* led) {
        int computer_instance = instance - 1;
        if (category < 0 || category >= 16 || computer_instance < 0) return;

        auto &leds = id(global_led_registry)[category];
        auto &faults = id(global_instance_faults)[category];

        // Ensure vectors are large enough
        if (leds.size() <= computer_instance) {
          leds.resize(computer_instance + 1, nullptr);
          faults.resize(computer_instance + 1, false);
        }
        
        // Assign the LED pointer
        leds[computer_instance] = led;
      }


output:
  - platform: template
    id: virtual_output
    type: binary
    write_action: []

# Fake light to act as a placeholder for LED control logic
light:
  - platform: binary
    id: virtual_status_light
    output: virtual_output


interval:
  - interval: 50ms
    then:
      - lambda: |-
          // --- STATIC STATE VARIABLES ---
          static int current_stage = 0;       
          static int active_category = -1;    
          static int pips_count = 0;          
          static uint32_t next_event_ms = 0;  
          static bool heartbeat_on = false;   

          // --- NON-BLOCKING TIMER CHECK ---
          uint32_t now = millis();
          if (now < next_event_ms) return;

          float bri = 0.5;

          switch (current_stage) {
            
            // =================================================================
            // STAGE 0: SEARCH & HEARTBEAT
            // =================================================================
            case 0: 
              // 1. Circular Scan
              for (int i = 1; i <= 16; i++) {
                int search_target = (active_category + i) % 16;
                bool is_faulted = (id(global_system_fault_mask) >> search_target) & 1;
                
                // CHECK FOR VALID LEDS
                bool has_valid_led = false;
                if (is_faulted) {
                    for (auto *ptr : id(global_led_registry)[search_target]) {
                        if (ptr != nullptr) {
                            has_valid_led = true;
                            break;
                        }
                    }
                    if (!has_valid_led) {
                        // THIS LOG WILL REVEAL THE ISSUE:
                        ESP_LOGW("fault_sm", "Ghost Fault detected! Cat %d is ON, but no LED assigned. Skipping.", search_target);
                    }
                }

                if (is_faulted && has_valid_led) {
                    active_category = search_target;
                    current_stage = 1; 
                    ESP_LOGD("fault_sm", "Fault Found: Cat %d. Moving to Stage 1.", active_category);
                    return; 
                }
              }

              // 2. Healthy Heartbeat
              if (!id(global_led_registry)[0].empty() && id(global_led_registry)[0][0] != nullptr) {
                auto call = id(global_led_registry)[0][0]->make_call();
                if (!heartbeat_on) {
                  if (${board_has_rgb}) { 
                    call.set_rgb(0.0, 1.0, 0.0);
                    call.set_brightness(bri);
                  }
                  call.set_state(true); 
                  ESP_LOGD("fault_sm", "Heartbeat ON");  // UNCOMMENTED
                } else { 
                  call.set_state(false); 
                  ESP_LOGD("fault_sm", "Heartbeat OFF"); // UNCOMMENTED
                }
                call.perform();
                heartbeat_on = !heartbeat_on;
                next_event_ms = now + 1000;
              } else {
                 // Debug if Heartbeat is failing to run
                 // ESP_LOGW("fault_sm", "Heartbeat skipped: No System LED configured.");
              }
              
              active_category = -1;
              return;

            // =================================================================
            // STAGE 1: HEADER
            // =================================================================
            case 1: 
              ESP_LOGD("fault_sm", "Stage 1: Blue Header Start"); // UNCOMMENTED
              for (size_t i = 0; i < id(global_led_registry)[active_category].size(); i++) {
                auto *led = id(global_led_registry)[active_category][i];
                auto &faults = id(global_instance_faults)[active_category];

                if (led != nullptr && i < faults.size() && faults[i]) {
                  auto call = led->make_call();
                  if (${board_has_rgb}) { 
                    call.set_rgb(0.0, 0.0, 1.0); 
                    call.set_brightness(bri);    
                  }
                  call.set_state(true);
                  call.perform();
                }
              }
              
              current_stage = 2; 
              pips_count = 0; 
              next_event_ms = now + 1000;
              break;

            // =================================================================
            // STAGE 2: PIPS
            // =================================================================
            case 2: 
              {
                int total_toggles = (active_category + 1) * 2; 
                bool is_on_cycle = (pips_count % 2 != 0); 
                
                for (size_t i = 0; i < id(global_led_registry)[active_category].size(); i++) {
                   auto *led = id(global_led_registry)[active_category][i];
                   auto &faults = id(global_instance_faults)[active_category];

                   if (led != nullptr && i < faults.size() && faults[i]) {
                    auto call = led->make_call();
                    if (is_on_cycle) {
                      if (${board_has_rgb}) { 
                        call.set_rgb(1.0, 0.0, 0.0); 
                        call.set_brightness(bri);    
                      }
                      call.set_state(true);
                    } else { 
                      call.set_state(false); 
                    }
                    call.perform();
                  }
                }
                
                pips_count++;

                if (pips_count < total_toggles) {
                   int delay = (pips_count > 0 && pips_count % 8 == 0) ? 500 : 150;
                   next_event_ms = now + delay;
                } else {
                   ESP_LOGD("fault_sm", "Stage 2 Complete. Gap starting.");
                   current_stage = 3; 
                   next_event_ms = now + 1000;
                }
              }
              break;

            // =================================================================
            // STAGE 3: GAP (RESET)
            // =================================================================
            case 3: 
              // Bounds check safety to prevent crash
              if (active_category >= 0 && active_category < 16) {
                  for (auto *led : id(global_led_registry)[active_category]) {
                    if (led != nullptr) {
                      auto call = led->make_call();
                      call.set_state(false);
                      call.perform();
                    }
                  }
              }
              ESP_LOGD("fault_sm", "Stage 3 Complete. Resetting to Search."); // UNCOMMENTED
              current_stage = 0; 
              // IMPORTANT: No delay here, go straight to search next cycle
              next_event_ms = now; 
              break;
          }