# Updated : 2026.01.31
# Version : 1.1.2
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.


substitutions:
  global_status_led: "esp_light"

globals:
  # 2D grid of physical LED pointers
  # Structure: [Component Category (0-15)] -> [Specific Instance ID (0-N)]
  - id: global_led_registry
    type: std::vector<std::vector<esphome::light::LightState*>>
    initial_value: 'std::vector<std::vector<esphome::light::LightState*>>(16)'

  # ---------------------------------------------------------
  # Global Function: Update LED assignment
  # ---------------------------------------------------------
  - id: global_register_led
    type: std::function<void(int, int, light::LightState*)>
    initial_value: |-
      [](int category, int instance, light::LightState* led) {

        if (led == &id(virtual_status_light)) {
            led = nullptr; 
        }

        int computer_instance = instance - 1;
        if (category < 0 || category >= 16 || computer_instance < 0) return;

        auto &leds = id(global_led_registry)[category];
        auto &faults = id(global_instance_faults)[category];

        if (leds.size() <= computer_instance) {
          leds.resize(computer_instance + 1, nullptr);
          faults.resize(computer_instance + 1, false);
        }
        leds[computer_instance] = led;
      }


output:
  - platform: template
    id: virtual_output
    type: binary
    write_action: []

# Fake light to act as a placeholder for LED control logic
light:
  - platform: binary
    id: virtual_status_light
    output: virtual_output


interval:
  - interval: 50ms
    then:
      - lambda: |-
          // -----------------------------------------------------------------------
          // STATE MANAGEMENT
          // -----------------------------------------------------------------------
          struct LedStateContext {
              size_t fault_index;
              int last_cycle_id;
          };

          // Static variables persist between lambda calls
          static std::map<esphome::light::LightState*, LedStateContext> states;
          static uint32_t cycle_start_ms = 0;
          static uint32_t current_cycle_duration = 2000;
          static int global_cycle_count = 0;

          // -----------------------------------------------------------------------
          // STEP 1: DYNAMIC TIMING CALCULATION
          // -----------------------------------------------------------------------
          uint32_t now = millis();
          int32_t time_into_cycle = now - cycle_start_ms;

          // Check if the current cycle has expired
          if (time_into_cycle >= current_cycle_duration || time_into_cycle < 0) {
              
              // RESET: Start a new cycle
              cycle_start_ms = now;
              time_into_cycle = 0;
              global_cycle_count++;

              // Scan entire system to find the "worst case" fault currently active
              int max_active_category = -1;

              for (int cat = 0; cat < 16; cat++) {
                  auto &faults = id(global_instance_faults)[cat];
                  for (bool f : faults) {
                      if (f) {
                          if (cat > max_active_category) max_active_category = cat;
                          break; // Found a fault in this cat, move to next cat
                      }
                  }
              }

              // Calculate required duration
              if (max_active_category == -1) {
                  // System Healthy: Default to 2s (1s ON, 1s OFF)
                  current_cycle_duration = 2000;
              } else {
                  // System Faulted: Calculate exact time needed
                  // Duration = Header(1000) + Gap(500) + (Pips * 300) + Padding(500)
                  int pips = max_active_category + 1;
                  current_cycle_duration = 1500 + (pips * 300) + 500;
                  
                  // Enforce 2s minimum so the Green/Blue Header (1s) doesn't look like a strobe
                  if (current_cycle_duration < 2000) current_cycle_duration = 2000;
              }
          }

          // -----------------------------------------------------------------------
          // STEP 2: MAP REGISTRY TO PHYSICAL LEDS
          // -----------------------------------------------------------------------
          std::map<esphome::light::LightState*, std::vector<std::pair<int, int>>> assignments;
          
          for (int cat = 0; cat < 16; cat++) {
             auto &leds_in_cat = id(global_led_registry)[cat];
             for (size_t inst = 0; inst < leds_in_cat.size(); inst++) {
                 auto *led = leds_in_cat[inst];
                 if (led != nullptr) assignments[led].push_back({cat, (int)inst});
             }
          }

          // -----------------------------------------------------------------------
          // STEP 3: UPDATE LEDS
          // -----------------------------------------------------------------------
          // Spotlight Logic: Header is valid only in the first 1000ms
          bool is_header_phase = (time_into_cycle < 1000);

          for (auto const& [led, assigned_list] : assignments) {
              
              // A. Identify Active Faults for this LED
              std::vector<int> active_fault_categories;
              for (auto &pair : assigned_list) {
                  int cat = pair.first;
                  int inst = pair.second;
                  auto &cat_faults = id(global_instance_faults)[cat];
                  if (inst < cat_faults.size() && cat_faults[inst]) {
                      active_fault_categories.push_back(cat);
                  }
              }

              LedStateContext &ctx = states[led];
              float bri = 0.5;
              auto call = led->make_call();

              // CASE 1: UNASSIGNED
              if (assigned_list.empty()) {
                  call.set_state(false).perform();
                  continue;
              }

              // CASE 2: HEALTHY (Green Sync)
              if (active_fault_categories.empty()) {
                  ctx.fault_index = 0;
                  if (is_header_phase) {
                      if (${board_has_rgb}) call.set_rgb(0.0, 1.0, 0.0);
                      call.set_brightness(bri).set_state(true);
                  } else {
                      call.set_state(false);
                  }
                  call.perform();
                  continue;
              }

              // CASE 3: FAULTED (Blue Sync)
              
              // Update Rotation on Cycle Change
              if (ctx.last_cycle_id != global_cycle_count) {
                  ctx.last_cycle_id = global_cycle_count;
                  ctx.fault_index++;
                  if (ctx.fault_index >= active_fault_categories.size()) ctx.fault_index = 0;
              }

              int current_cat = active_fault_categories[ctx.fault_index];
              int pips_needed = current_cat + 1;

              // Phase A: Header (0 - 1000ms)
              if (time_into_cycle < 1000) {
                  if (${board_has_rgb}) call.set_rgb(0.0, 0.0, 1.0);
                  call.set_brightness(bri).set_state(true);
                  call.perform();
                  continue;
              }

              // Phase B: Gap (1000 - 1500ms)
              if (time_into_cycle < 1500) {
                  call.set_state(false).perform();
                  continue;
              }

              // Phase C: Pips (1500ms -> End)
              uint32_t pip_phase_time = time_into_cycle - 1500;
              int current_pip_index = pip_phase_time / 300; 
              uint32_t within_pip = pip_phase_time % 300;

              if (current_pip_index < pips_needed) {
                  if (within_pip < 150) {
                      if (${board_has_rgb}) call.set_rgb(1.0, 0.0, 0.0);
                      call.set_brightness(bri).set_state(true);
                  } else {
                      call.set_state(false);
                  }
              } else {
                  call.set_state(false); // Wait for next cycle
              }
              call.perform();
          }



  # LED Assignment Report in logs, enabled via enable_led_logging substitution
  - interval: 60s
    then:
      - lambda: |-
          // If the substitution is false, stop
          if (!${enable_led_logging}) return;

          ESP_LOGI("led_rpt", "┌──────────────────────────────┐");
          ESP_LOGI("led_rpt", "│    LED REGISTRY ASSIGNMENT   │");
          ESP_LOGI("led_rpt", "└──────────────────────────────┘");

          bool registry_empty = true;

          for (int cat = 0; cat < 16; cat++) {
            // Access the LED Registry
            auto &leds = id(global_led_registry)[cat];
            
            // Skip empty categories
            if (leds.empty()) continue;
            registry_empty = false;

            // Translate ID to Name
            std::string cat_name;
            switch(cat) {
                case 0: cat_name = "SYSTEM     "; break;
                case 1: cat_name = "BMS        "; break;
                case 2: cat_name = "CAN->INV   "; break;
                case 3: cat_name = "RS485->INV "; break;
                case 4: cat_name = "SHUNT      "; break;
                case 5: cat_name = "BALANCER   "; break;
                case 6: cat_name = "NETWORK    "; break;
                case 7: cat_name = "AUX 1      "; break;
                default: cat_name = "CAT_" + to_string(cat) + "     "; break;
            }

            // Build the status string for this category's LEDs
            std::string status_line = "";
            
            for (size_t i = 0; i < leds.size(); i++) {
                // Check if the pointer is valid
                if (leds[i] != nullptr) {
                    status_line += "[LINK] ";
                } else {
                    status_line += "[NULL] ";
                }
            }

            ESP_LOGI("led_rpt", "   %s: %s", cat_name.c_str(), status_line.c_str());
          }

          if (registry_empty) {
             ESP_LOGW("led_rpt", ">> WARNING: NO LEDS REGISTERED");
          }
          ESP_LOGI("led_rpt", "--------------------------------");
